name: Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DeployFE

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v20.18.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build project
        run: |
          npm run build --if-present

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          NODE_ENV: production
